version: '2'

services:
  rabbit-local:
    image: rabbitmq:3.7.15-management
    container_name: rabbit-local
    hostname: localhost
    ports:
      - 15672:15672
      - 5672:5672

networks:
  db_sharing:
